version: '3.9'
services:
  postgres:
    restart: always
    image: postgres:16
    environment:
      - POSTGRES_USER=postuser
      - POSTGRES_PASSWORD=jkk3i92jfjrio
    ports: 
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pg-admin:
    restart: always
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=nephewtechnologies@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=ekju3892jejke
      - PGADMIN_LISTEN_PORT=5050
    ports: 
      - 5050:5050