services:
  mysql:
    image: mysql:latest
    container_name: mysql-npt
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: npt-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: {}